apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
  namespace: uat
type: kubernetes.io/dockerconfigjson
data:
  # This is a placeholder â€” GitHub Actions pipeline
  # creates the real secret automatically during deploy.
  # Do NOT put real passwords here.
  .dockerconfigjson: e30K
