name: Build and Push to Harbor

on:
  push:
    branches:
      - main

env:
  REGISTRY: harbor.opsmonsters.in
  PROJECT: demo
  IMAGE_NAME: myapp
<<<<<<< HEAD
=======
  TAG: latest
>>>>>>> 309764ea0f4ff5e322cec9eee23eb4d2161b4aad

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Harbor
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - name: Set image tag
      run: |
        echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build \
          -t $REGISTRY/$PROJECT/$IMAGE_NAME:$IMAGE_TAG \
          -t $REGISTRY/$PROJECT/$IMAGE_NAME:latest \
          .

    - name: Push Docker image
      run: |
        docker push $REGISTRY/$PROJECT/$IMAGE_NAME:$IMAGE_TAG
        docker push $REGISTRY/$PROJECT/$IMAGE_NAME:latest
=======
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.PROJECT }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .

      - name: Push Docker Image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.PROJECT }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
>>>>>>> 309764ea0f4ff5e322cec9eee23eb4d2161b4aad
